server:
  port: 3032
  servlet:
    contextPath: /api/logs-service

spring:
  cassandra:
    port: 9042
    contact-points: mycassandra
    keyspace-name: mykeyspace
    #local-datacenter: datacenter1
    #entity-base-package: com.example.cassandra.springbootcassandrademo.model