version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_BD: shop_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
