server:
  port: 3031
  servlet:
    contextPath: /api/notification-service

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification_service_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest