server:
  port: 3030
  servlet:
    contextPath: /api/shop-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/shop_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true