server:
  port: 3034
  servlet:
    contextPath: /api/user-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true